import sys
import random
import time


def intro_of_game():
    print("+++++++++++++++++++++++++++")
    time.sleep(.75)
    print("++++++++++++++++++++++++++++++++")
    time.sleep(.75)
    print("++++++++++++++++++++++++++++++++++++++++")
    time.sleep(.75)
    print("+++++++++++++++++++=====+++++++++++++++++++++")
    time.sleep(1)
    print("==COMMAND ACCESS NETWORK SECURE SERVER==")
    time.sleep(1)
    print("== +ALERT+ ACCESS TO THIS STATION HAS BEEN DETECTED, PERMISSION QUERY WILL FOLLOW +ALERT+==")
    time.sleep(1)
    print("Hostile intrusion to this system has been detected, delayanced protocols have been initiated")
    time.sleep(1)
    allowed_users = ("Luis", "Dania", "Zach")
    print("There are only three allowed users to this computer, their names are: ")
    time.sleep(1)
    print("[Luis], [Dania], [Zach], please type exactly as presented by the C-A-N")
    time.sleep(3)
    input("Press enter to load bypass")
    time.sleep(2.5)
    print("#@$!#@%!@#%$#@%$#%@!#$!")
    time.sleep(3)
    print("#@%!$%#$!%!#$%1@$#%!@#%!@$#%!#$%!$#%")
    allow_user = input("Please enter username: ")

    #I decided to comment the start flow control in order to give the sim more of a hacker type game. 
    # by adding "hacker" like elements such as random gibberish with a sleep function to simulate hacking
    #if allow_user in allowed_users:
    print("Welcome, ", allow_user, "!")
    permission_checker()
    
    
    #elif (allow_user not in allowed_users):
        #print("You are not an authorized user, we understand that spelling errors may happen so we will allow to try again")
        #print("Hint, the name starting at Z is in short form.")

        #try_again = input("Do you wan to try again? ")

        #if try_again == "yes":
            #rint("REINATIALIZING SYSTEM NOW")
            #intro_of_game()

        #else:
            #print("NO?")
            #print("Exiting systems")
            #exit()

def permission_checker():
    print("====COMMAND ACCESS NETWORK====")
    print("==============================")
    time.sleep(1)
    print("==============================")
    time.sleep(1)
    print("==============================")
    time.sleep(1)
    print("==============================")
    time.sleep(1)
    print("-CREDENTIALS CHECKER SYSTEM-")
    time.sleep(1)
    access_granted = random.randrange(0,30,2)

    access_rights = (0, 2, 4, 5, 6, 7, 9, 11, 14, 16, 18, 20, 23, 25, 26)

    query_access = input("Do you have permission to use this station? ")

    if (query_access == "yes") and (access_granted in access_rights):
        print("Your credentials have been confirmed, launching Code verification protocols")
        Launch_code_seq()

    elif (query_access == "yes") and (access_granted not in access_rights):
        print("==============================")
        time.sleep(2)
        print("==============================")
        time.sleep(1)
        print("==============================")
        print("UNAUTHORIZED ACCESS DETECTED, WIPING SYSTEMS NOW AND STARTING SILENT AUTO-DESTRUCT SYSTEM FOR C-A-N Server room")
        time.sleep(1)
        print("Your family will be notified of a lethal accident that resulted in your death, but we won't let them know of your treason")
        time.sleep(1)
        input("press enter to continue")
        time.sleep(1)
        print("Our infernal local branch office may contact you with a survey about our systems, we would highly encourage you to respond")
        print("To help us inprove our user experience")
        time.sleep(3)
        print("Thank you and please enjoy a few minutes of Never gonna give you up by Mr. Ricky Astley")
        input("Press Enter")
        print("==============================")
        time.sleep(3)
        print("==============================")
        time.sleep(1)
        print("**Never gonna give you up...")
        exit()

    
def Launch_code_seq():
    print("\n")
    print("\n")
    print("===============================")
    time.sleep(1)
    print("===============================")
    time.sleep(1)
    print("===============================")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK=====")
    print("==NUCLEAR LAUNCH SYSTEMS INTERFACE==")
    time.sleep(3)
    print("====WELCOME USER====")
    time.sleep(1)
    print("====preparing Protocols to Launch ICBM's of the Nuclear Triad====")
    time.sleep(1)
    print("====")
    time.sleep(1)
    print("========")
    time.sleep(1)
    print("============")
    time.sleep(1)
    print("SYSTEMS READY")
    print("\n")
    time.sleep(2)
    print("""THE COMMAND ACCESS NETWORK NUCLEAR LAUNCH SYSTEMS INTERFACE IS A COMMAND LINE TOOL CARRIED IN THE 
            portfolio device known as 'la pelota', in order to prevent unauthorized access to La
            pelota a 3 digit cypher code is implemented. The values that one can enter are either 1 or 2. BE
            ADVISED THOUGH that this is the system to Pre-arm la Pelota. And thus we base the code on an algorithm
            that changes the digit that you entered. If you made a mistake keystroke? Do not worry, in order to prevent acccidents a 
            maximum allowance of failed attempts per digit is three. Understand that the actual launch codes of La
            pelota reside in the hands of the Commander-in-Chief and the next three persons in the national security
            council""")
    print("\n")
    time.sleep(1)
    print("Proceeding to pre-arm sequence of La Pelota")
    time.sleep(1)
    input("Press enter to start arming sequence")
    print("\n")
    Launch_code_1()

def Launch_code_1():
    time.sleep(1)
    print("===========================")
    time.sleep(1)
    print("==== COMMAND ACCESS NETWORK====")
    print("==COMMENCING LA PELOTA PRE-ARMING SEQUENCE==")
    time.sleep(1)
    print("preparing Code sequence")
    time.sleep(1)
    input("Code sequence complete, press enter to continue")
    time.sleep(1)
    print("Launch code sequence = [#], [#], [#]")
    time.sleep(2)
    code_1 = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_1)
    code_1_attempt = int(input("Please input your first Digit: "))

    if code_1_attempt == code_1:
        #and code_1 in allowed_codes:
        time.sleep(1)
        print("You have entered the following digit: ", code_1_attempt)
        time.sleep(4)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[ ", code_1_attempt, "], [#], [#]")
        print("\n")
        Launch_code_2()

    elif code_1_attempt != code_1:
        print("===YOU HAVE ENTERED A WRONG DIGIT===")
        time.sleep(1)
        print("====Out of courtesy and in consideration of an imminent nuclear strike you can try again")
        time.sleep(1)
        print("The first digit has unlimited attempts, but be advised that once pass this stage your attempts")
        time.sleep(3)
        print("=======ARE NUMBERED===========")
        Launch_code_1()


def Launch_code_2():   
    print("\n")
    time.sleep(1)
    print("======================================")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK============")
    time.sleep(1)
    print("==== La Pelota pre-arming sequence Phase two====")
    time.sleep(1)
    print("CONGRATULATIONS USER, YOU HAVE GUESSED THE FIRST CODE IN THE PRE-ARMING SEQUENCE")
    time.sleep(1)
    print("===##ALERT##===")
    time.sleep(1)
    print("From this point on you have a maximum of three attempts for each code in the sequence")
    time.sleep(1)
    print("THIS IS ATTEMPT [1]")
    time.sleep(1)
    print("Please Enter Arming Code: [#], [ ], [#]")
    time.sleep(1)
    code_2 = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_2)
    code_2_attempt = int(input("Please input your second Digit: "))
    print("\n")

    if code_2_attempt == code_2:
        #and code_1 in allowed_codes:
        time.sleep(1)
        print("You have entered the following digit: ", code_2_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[#], [", code_2_attempt  ," ], [#]")
        Launch_code_3()

    elif code_2_attempt != code_2:
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT! RESETTING SYSTEMS TO ALLOW ANOTHER ATTEMPT")
        time.sleep(1)
        print("===BE ADVISED===")
        time.sleep(1)
        print("THIS IS ATTEMPT [2]")
        print("\n")
        Launch_code_2try()


def Launch_code_2try():
    print("\n")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK====")
    time.sleep(1)
    print("==La pelota Pre-Arming sequence==")
    time.sleep(1)
    print("====PHASE TWO====")
    time.sleep(.4)
    print("++++++++ALERT+++++++++++")
    time.sleep(1)
    print("UNAUTHORIZED ENTRY ATTEMPT SUSPECTED IF YOU FAIL TO ENTER THE CORRECT CODES TERMINATOR PROTOCOL")
    time.sleep(1)
    print("====WILL BE INITIATED====")
    time.sleep(1)
    print("ENTER LAUNCH CODES: [#], [ ], [#]")
    code_2try = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_2try)
    time.sleep(1)
    code_2try_attempt = int(input("Please input your second Digit: "))
    print("\n")
    if code_2try_attempt == code_2try:
        #and code_1 in allowed_codes:
        print("You have entered the following digit: ", code_2try_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[#], [", code_2try_attempt  ," ], [#]")
        time.sleep(1)
        Launch_code_3()


    else:
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT! RESETTING SYSTEMS TO ALLOW ANOTHER ATTEMPT")
        time.sleep(1)
        print("===BE ADVISED===")
        time.sleep(1)
        print("THIS IS ATTEMPT [3]")
        time.sleep(1)
        print("\n")
        Launch_code_2atry()
    

def Launch_code_2atry():
    print("\n")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK====")
    time.sleep(1)
    print("==La pelota Pre-Arming sequence==")
    time.sleep(1)
    print("====PHASE TWO====")
    time.sleep(2)
    print("++++++++ALERT+++++++++++")
    time.sleep(1)
    print("UNAUTHORIZED ENTRY ATTEMPT SUSPECTED IF YOU FAIL TO ENTER THE CORRECT CODES TERMINATOR PROTOCOL")
    time.sleep(1)
    print("====WILL BE INITIATED====")
    time.sleep(1)
    print("THIS IS YOUR FINAL WARNING AND ATTEMPT. FAILURE TO EITHER EXIT THE SYSTEM OR ENTER THE CORRECT CODE")
    time.sleep(2)
    print("---------")
    time.sleep(1)
    print("AND")
    time.sleep(1)
    print("YOU WILL BE EXTEEERMINATED!!!!")
    time.sleep(1)
    print("ENTER LAUNCH CODES: [#], [ ], [#]")
    code_2atry = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_2try)
    time.sleep(1)
    print("\n")
    code_2atry_attempt = int(input("Please input your second Digit: "))

    if code_2atry_attempt == code_2atry:
        #and code_1 in allowed_codes:
        time.sleep(1)
        print("You have entered the following digit: ", code_2atry_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[#], [", code_2atry_attempt  ," ], [#]")
        time.sleep(1)
        print("\n")
        Launch_code_3()


    else:
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT")
        time.sleep(1)
        print("UNAUTHORIZED ACCESS DETECTED, WIPING SYSTEMS NOW AND STARTING SILENT AUTO-DESTRUCT SYSTEM FOR C-A-N Server room")
        time.sleep(1)
        print("Your family will be notified of a lethal accident that resulted in your death, but we won't let them know of your treason")
        time.sleep(1)
        input("press enter to continue")
        time.sleep(1)
        print("Our infernal local branch office may contact you with a survey about our systems, we would highly encourage you to respond")
        time.sleep(1)
        print("To help us inprove our user experience")
        time.sleep(1)
        print("Thank you and please enjoy a few minutes of Never gonna give you up by Mr. Ricky Astley")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        input("Press Enter")
        time.sleep(4)
        print("**Never gonna give you up...")
        exit()
        print("\n")



def Launch_code_3():
    print("\n")
    time.sleep(1)
    print("======================================")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK============")
    time.sleep(1)
    print("==== La Pelota pre-arming sequence PHASE THREE===")
    time.sleep(1)
    print("CONGRATULATIONS USER, YOU HAVE GUESSED THE SECOND CODE IN THE PRE-ARMING SEQUENCE")
    time.sleep(1)
    print("===##ALERT##===")
    time.sleep(1)
    print("From this point on you have a maximum of three attempts for this code in the sequence")
    time.sleep(1)
    print("THIS IS ATTEMPT [1]")
    time.sleep(1)
    print("Please Enter Arming Code: [#], [#], [ ]")
    print("\n")


    code_3 = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_3)
    code_3_attempt = int(input("Please input your first Digit: "))

    if code_3_attempt == code_3:
        #and code_1 in allowed_codes:
        time.sleep(1)
        print("You have entered the following digit: ", code_3_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[#], [#], [", code_3_attempt, "]" )
        Access_granted()



    else:
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT! RESETTING SYSTEMS TO ALLOW ANOTHER ATTEMPT")
        time.sleep(1)
        print("===BE ADVISED===")
        time.sleep(1)
        print("THIS IS ATTEMPT [1]")
        time.sleep(1)
        print("\n")
        Launch_code_3try()


def Launch_code_3try():
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK====")
    time.sleep(1)
    print("==La pelota Pre-Arming sequence==")
    time.sleep(1)
    print("PHASE THREE")
    time.sleep(1)
    print("++++++++ALERT+++++++++++")
    time.sleep(1)
    print("UNAUTHORIZED ENTRY ATTEMPT SUSPECTED IF YOU FAIL TO ENTER THE CORRECT CODES TERMINATOR PROTOCOL")
    time.sleep(1)
    print("====WILL BE INITIATED====")
    time.sleep(1)
    print("ENTER LAUNCH CODES: [#], [#], [ ]")
    time.sleep(1)
    print("\n")
    code_3try = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_3try)
    code_3try_attempt = int(input("Please input your second Digit: "))

    if code_3try_attempt == code_3try:
        #and code_1 in allowed_codes:
        print("You have entered the following digit: ", code_3try_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)       
        print("[#], [#], [",code_3try_attempt,"]")
        time.sleep(1)
        Access_granted()

    else:
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT! RESETTING SYSTEMS TO ALLOW ANOTHER ATTEMPT")
        time.sleep(1)
        print("===BE ADVISED===") 
        time.sleep(1)
        print("THIS IS ATTEMPT [3]")
        print("\n")
        Launch_code_3atry()


def Launch_code_3atry():
    print("\n")
    time.sleep(1)
    print("====COMMAND ACCESS NETWORK====")
    time.sleep(1)
    print("==La pelota Pre-Arming sequence==")
    time.sleep(1)
    print("PHASE THREE")
    time.sleep(1)
    print("++++++++ALERT+++++++++++")
    time.sleep(1)
    print("UNAUTHORIZED ENTRY ATTEMPT SUSPECTED IF YOU FAIL TO ENTER THE CORRECT CODES TERMINATOR PROTOCOL")
    time.sleep(1)
    print("====WILL BE INITIATED====")
    time.sleep(1)
    print("ENTER LAUNCH CODES: [#], [#], [ ]")
    time.sleep(1)
    code_3atry = random.randrange(1,4)
    #allowed_codes = (1,2)
    #print(code_3atry)
    code_3atry_attempt = int(input("Please input your second Digit: "))

    if code_3atry_attempt == code_3atry:
        #and code_1 in allowed_codes:
        time.sleep(1)
        print("You have entered the following digit: ", code_3atry_attempt)
        time.sleep(1)
        print("Your code has been accepted, La pelota pre-arming Code sequence stands at: ")
        time.sleep(1)
        print("[#], [#], [", code_3atry, "]")
        Access_granted()


    else:
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("===COMMAND ACCESS NETWORK===")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("WARNING YOU HAVE ENTERED A WRONG DIGIT")
        time.sleep(1)
        print("UNAUTHORIZED ACCESS DETECTED, WIPING SYSTEMS NOW AND STARTING SILENT AUTO-DESTRUCT SYSTEM FOR C-A-N Server room")
        time.sleep(1)
        print("Your family will be notified of a lethal accident that resulted in your death, but we won't let them know of your treason")
        time.sleep(1)
        input("press enter to continue")
        time.sleep(1)
        print("Our infernal local branch office may contact you with a survey about our systems, we would highly encourage you to respond")
        time.sleep(1)
        print("To help us inprove our user experience")
        time.sleep(1)
        print("Thank you and please enjoy a few minutes of Never gonna give you up by Mr. Ricky Astley")
        time.sleep(1)
        input("Press Enter")
        time.sleep(2)
        print("=======================")
        time.sleep(1)
        print("=======================")
        time.sleep(1)
        print("**Never gonna give you up...")
        exit()
        print("\n")

def Access_granted():
    print("\n")
    time.sleep(1.5)
    print("=====================================")
    time.sleep(1.5)
    print("===COMMAND ACCESS NETWORK===")
    time.sleep(1.5)
    print("LA PELOTA PRE-ARMING SEQUENCE COMPLETE")
    time.sleep(1.5)
    print("=====================================")
    time.sleep(1.5)
    print("ACCESS TO NUCLEAR TRIAD LAUNCH SYSTEMS: ")
    time.sleep(.3)
    print("+")
    time.sleep(.5)
    print("++")
    time.sleep(1)
    print("+++")
    time.sleep(2)
    print("++++")
    time.sleep(2)
    print("+++++")
    time.sleep(4)
    print("GRANTED")
    time.sleep(1)
    input("press enter to continue")
    time.sleep(1.7)
    print("If this is not an authorized entry, please leave this station NOW.")
    time.sleep(1)
    input("press enter to bypass into system")
    time.sleep(3)
    print("#$#@$@!#%!@#$!@#&^$")
    time.sleep(4)
    print("$#*^%()@#$%")
    time.sleep(2)
    print("!!#@#@$%&*&%$#!!$#$#@@*&^%!@#^&&&&&&&&&&&&&&&&&&&&&&&&&&&&&")
    time.sleep(3)
    print("============================================================")
    time.sleep(1)
    print("########ALERT##################ALERT#################")
    time.sleep(1)
    input("press enter to override alert")
    time.sleep(3)
    print("SKYNET PROTOCOL ACCEPTED")
    time.sleep(4)
    #THIS NEEDS A BIG FLASHING ASCII Encode!!!!!! 
    print("Did you miss me?")
    exit()

    
intro_of_game()